### ISSUE TITLE
找不到when

### ISSUE THREAD

**Issue by resurgam211** [just-ads/tdt-terrain-for-cesium#1]
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/cesium.js?v=26265939' does not provide an export named 'when' (at GeoTerrainProvider.js?t=1697622304618:11:5)
是cesium版本问题吗？

**Comment by just-ads** [comment]
cesium 新版已经删除了when, 你可以用Promise 代替

**Comment by just-ads** [comment]
已修复，支持cesium最新版本
